name: PR

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Setup node
      uses: actions/setup-node@v2

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm i
    
    - name: Build specs
      run: npm run build:test

    - name: Run unit tests
      run: npm run test

    - name: Build bundle
      run: npm run build:deploy
